name: storyrama ci
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      - run: yarn
      - run: yarn build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-1

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.12
      - uses: ./.github/actions/terraform
        with:
          environment: dev
          path: terraform
          # key:

      # - name: terraform init
      #   working-directory: ./terraform
      #   run: terraform init
      # - name: terraform plan
      #   working-directory: ./terraform
      #   run: terraform plan
