name: storyrama ci
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      - run: yarn
      - run: yarn build
      - uses: actions/terraform@v1
