name: storyrama ci
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      - run: yarn
      - run: yarn build
      - uses: hashicorp/terraform-github-actions@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: terraform init
        run: tf init
      - name: terraform plan
        run: tf plan
